# Generated by Django 3.2.5 on 2021-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerModel',
            fields=[
                ('FreelancerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Name', models.TextField()),
                ('City', models.TextField()),
                ('Country', models.TextField()),
                ('EducationalInstitution', models.TextField()),
                ('EducationalQualifications', models.TextField()),
                ('Employment', models.TextField()),
                ('CompanyName', models.TextField()),
                ('Skills', models.TextField()),
                ('CategoryName', models.TextField()),
                ('Email', models.TextField()),
                ('AdditionalContactDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('JobID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientName', models.TextField()),
                ('ClientCompanyName', models.TextField()),
                ('ClientEmail', models.TextField()),
                ('ClientCity', models.TextField()),
                ('ClientCountry', models.TextField()),
                ('Headline', models.TextField()),
                ('Description', models.TextField()),
                ('Skills', models.TextField()),
                ('AdditionalRequirements', models.TextField()),
                ('CategoryName', models.TextField()),
                ('Status', models.TextField()),
                ('ClientComment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvitedModel',
            fields=[
                ('JobID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientName', models.TextField()),
                ('ClientCompanyName', models.TextField()),
                ('ClientEmail', models.TextField()),
                ('ClientCity', models.TextField()),
                ('ClientCountry', models.TextField()),
                ('Headline', models.TextField()),
                ('Description', models.TextField()),
                ('Skills', models.TextField()),
                ('AdditionalRequirements', models.TextField()),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('JobID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientName', models.TextField()),
                ('CompanyName', models.TextField()),
                ('Email', models.TextField()),
                ('City', models.TextField()),
                ('Country', models.TextField()),
                ('Headline', models.TextField()),
                ('Description', models.TextField()),
                ('Skills', models.TextField()),
                ('AdditionalRequirements', models.TextField()),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('JobID', models.IntegerField(primary_key=True, serialize=False)),
                ('ClientName', models.TextField()),
                ('ClientCompanyName', models.TextField()),
                ('ClientEmail', models.TextField()),
                ('ClientCity', models.TextField()),
                ('ClientCountry', models.TextField()),
                ('Headline', models.TextField()),
                ('Description', models.TextField()),
                ('Skills', models.TextField()),
                ('AdditionalRequirements', models.TextField()),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewMyProfileModel',
            fields=[
                ('FreelancerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('Name', models.TextField()),
                ('City', models.TextField()),
                ('Country', models.TextField()),
                ('EducationalInstitution', models.TextField()),
                ('EducationalQualifications', models.TextField()),
                ('Employment', models.TextField()),
                ('CompanyName', models.TextField()),
                ('Skills', models.TextField()),
                ('CategoryName', models.TextField()),
                ('Email', models.TextField()),
                ('AdditionalContactDetails', models.TextField()),
            ],
        ),
    ]
