# Generated by Django 3.2.5 on 2021-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreelancerViewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewFreelancerProfileModel',
            fields=[
                ('FreelancerID', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Username', models.TextField()),
                ('Name', models.TextField()),
                ('City', models.TextField()),
                ('Country', models.TextField()),
                ('EducationalInstitution', models.TextField()),
                ('EducationalQualifications', models.TextField()),
                ('Employment', models.TextField()),
                ('CompanyName', models.TextField()),
                ('Skills', models.TextField()),
                ('CategoryName', models.TextField()),
                ('Email', models.TextField()),
                ('AdditionalContactDetails', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historymodel',
            name='Rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
