# Generated by Django 3.2.5 on 2021-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticFilesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('imagefile', models.ImageField(upload_to='images')),
            ],
        ),
    ]
