# Generated by Django 3.2.5 on 2021-09-15 17:56

import StaticFilesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticFilesApp', '0002_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.RemoveField(
            model_name='profilepicture',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='imagefile',
            field=models.ImageField(default='/image.png', upload_to=StaticFilesApp.models.upload_to),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='username',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
